### ISSUE TITLE
Project Team needs Environment Build Instructions (DEV and QA)

### ISSUE THREAD

**Issue by torpedo51** [Team4019/team4019-2017#4]
I'd like Cameron to produce an Installation Manual (PDF or HTML format) and attach it either to the Wiki or place it inside of the /artifacts folder.

Cameron, please work with Cooper to get all of the details.  When you're finished, Cameron will help each developer walk through the procedure to get set up and running.  The Manual should include these sections:

**Software Requirements**
- JRE/JDK (what version)
- Intellij (what version)
--        Installation settings required for our project
--        Plugins or libraries required, where to get them and how to install them
- GitKraken (what version
--         Installation settings required for our project
- Additional Tools as required

**Procedure to download (clone) the GitHub repository to a local environment**
1.  Create a local folder to store the code (e.g. \users\tim\Team4019-2017
2.  Start GitKraken
3.  Select "Clone Repository"
4.  Provide these values to the clone wizard: ... ... ...
5.  etc.

**Environment Verification**
1. From a command line, do this: $> _ _ _ _  and expect this result (e.g. "version 1.2")
2. etc.

**Basic Check-out and Check-in procedure**
 (provide a harmless example that we can actually do)
1. Pull the repository to make sure you have all of the latest code
2. Make a change to the readme.txt file (add your name to the top)
3. Check-in your change
4. verify the change by looking at the file on the Online (not local) GItHub repository

**Comment by cooperuser** [comment]
Pushed the new version of the repo with an updated [README.md](https://github.com/Team4019/team4019-2017/blob/master/README.md). It gives instructions on how to get everything set up and ready to go.

**Comment by torpedo51** [comment]
Cooper, 
These instructions need more granularity.  For example, we don't know how to open the repository (there are options), select a branch (which branch do we want on our locals to start with), set the local folder for GitKraken, and which pull option to use (there are a few).  Can you and Cameron have another pass at this please?
Thanks

**Comment by torpedo51** [comment]
![invalid references error](https://cloud.githubusercontent.com/assets/24976387/22567253/12ae66d6-e944-11e6-8a56-dc5f5abfcdf5.png)
